// flow-typed signature: b170eb9ca1058ab04f2b699ef6e7a4fd
// flow-typed version: <<STUB>>/should_v^11.1.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'should'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'should' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'should/as-function' {
  declare module.exports: any;
}

declare module 'should/cjs/should' {
  declare module.exports: any;
}

declare module 'should/es6/should' {
  declare module.exports: any;
}

declare module 'should/should' {
  declare module.exports: any;
}

// Filename aliases
declare module 'should/as-function.js' {
  declare module.exports: $Exports<'should/as-function'>;
}
declare module 'should/cjs/should.js' {
  declare module.exports: $Exports<'should/cjs/should'>;
}
declare module 'should/es6/should.js' {
  declare module.exports: $Exports<'should/es6/should'>;
}
declare module 'should/index' {
  declare module.exports: $Exports<'should'>;
}
declare module 'should/index.js' {
  declare module.exports: $Exports<'should'>;
}
declare module 'should/should.js' {
  declare module.exports: $Exports<'should/should'>;
}
