import Model from '../lib/Model';
import {
  Error as _Error,
  RegExp as _RegExp,
} from '../lib/Type';

let _undefined;
const date = new Date(Date.UTC(2016, 1, 1));
const model = new Model();
const error = new Error('Foo');
const regex = /^abc/i;
const object = {foo: 1};

export default [
  ['undefined', _undefined, {
    Boolean: [false, false, false],
    Number: [false, NaN, 'throw'],
    String: [false, '', ''],
    Date: [false, _undefined, 'throw'],
    Array: [false, _undefined, _undefined],
    Model: [true, _undefined, _undefined],
    Error: [false, _undefined, 'throw'],
    RegExp: [false, _undefined, 'throw'],
    Any: [true, _undefined, _undefined],
    Mixed: [false, _undefined, _undefined],
    Embed: [false, {}, 'throw'],
  }],

  ['null', null, {
    Boolean: [false, false, false],
    Number: [false, 0, 0],
    String: [false, '', ''],
    Date: [false, new Date(null), new Date(null)],
    Array: [false, null, null],
    Model: [true, null, null],
    Error: [false, null, 'throw'],
    RegExp: [false, null, 'throw'],
    Any: [true, null, null, null],
    Mixed: [false, null, null],
    Embed: [false, {}, 'throw'],
  }],

  ['number 0', 0, {
    Boolean: [false, false, false],
    Number: [true, 0, 0],
    String: [false, '0', '0'],
    Date: [false, new Date(0), new Date(0)],
    Array: [false, 1, 1],
    Model: [true, 0, 0],
    Error: [false, 0, 'throw'],
    RegExp: [false, new _RegExp(0), new _RegExp(0)],
    Any: [true, 0, 0, 0],
    Mixed: [false, 0, 0],
    Embed: [false, {}, 'throw'],
  }],

  ['number 1', 1, {
    Boolean: [false, true, true],
    Number: [true, 1, 1],
    String: [false, '1', '1'],
    Date: [false, new Date(1), new Date(1)],
    Array: [false, 1, 1],
    Model: [true, 1, 1],
    Error: [false, 1, 'throw'],
    RegExp: [false, new _RegExp(1), new _RegExp(1)],
    Any: [true, 1, 1],
    Mixed: [false, 1, 1],
    Embed: [false, {}, 'throw'],
  }],

  ['integer', 42, {
    Boolean: [false, true, true],
    Number: [true, 42, 42],
    String: [false, '42', '42'],
    Date: [false, new Date(42), new Date(42)],
    Array: [false, 1, 1],
    Model: [true, 42, 42],
    Error: [false, 42, 'throw'],
    RegExp: [false, new _RegExp(42), new _RegExp(42)],
    Any: [true, 42, 42, 42],
    Mixed: [false, 42, 42],
    Embed: [false, {}, 'throw'],
  }],

  ['not a number', NaN, {
    Boolean: [false, false, false],
    Number: [false, NaN, 'throw'],
    String: [false, 'NaN', 'NaN'],
    Date: [false, NaN, 'throw'],
    Array: [false, NaN, NaN],
    Model: [true, NaN, NaN],
    Error: [false, NaN, 'throw'],
    RegExp: [false, NaN, 'throw'],
    Any: [true, NaN, NaN, NaN],
    Mixed: [false, NaN, NaN],
    Embed: [false, {}, 'throw'],
  }],

  ['infinity', Infinity, {
    Boolean: [false, true, true],
    Number: [false, Infinity, 'throw'],
    String: [false, 'Infinity', 'Infinity'],
    Date: [false, Infinity, 'throw'],
    Array: [false, Infinity, Infinity],
    Model: [true, Infinity, Infinity],
    Error: [false, Infinity, 'throw'],
    RegExp: [false, Infinity, 'throw'],
    Any: [true, Infinity, Infinity, Infinity],
    Mixed: [false, Infinity, Infinity],
    Embed: [false, {}, 'throw'],
  }],

  ['decimal', 1.34, {
    Boolean: [false, true, true],
    Number: [true, 1.34, 1.34],
    String: [false, '1.34', '1.34'],
    Date: [false, new Date(1.34), new Date(1.34)],
    Array: [false, 1.34, 1.34],
    Model: [true, 1.34, 1.34],
    Error: [false, 1.34, 'throw'],
    RegExp: [false, new _RegExp(1.34), new _RegExp(1.34)],
    Any: [true, 1.34, 1.34, 1.34],
    Mixed: [false, 1.34, 1.34],
    Embed: [false, {}, 'throw'],
  }],

  ['negative', -24, {
    Boolean: [false, true, true],
    Number: [true, -24, -24],
    String: [false, '-24', '-24'],
    Date: [false, new Date(-24), new Date(-24)],
    Array: [false, -24, -24],
    Model: [true, -24, -24],
    Error: [false, -24, 'throw'],
    RegExp: [false, new _RegExp(-24), new _RegExp(-24)],
    Any: [true, -24, -24, -24],
    Mixed: [false, -24, -24],
    Embed: [false, {}, 'throw'],
  }],

  ['empty string', '', {
    Boolean: [false, false, false],
    Number: [false, 0, 0],
    String: [true, '', ''],
    Date: [false, '', 'throw'],
    Array: [false, '', ''],
    Model: [true, '', ''],
    Error: [false, '', 'throw'],
    RegExp: [false, '', 'throw'],
    Any: [true, '', '', ''],
    Mixed: [false, '', ''],
    Embed: [false, {}, 'throw'],
  }],

  ['string', 'abc', {
    Boolean: [false, true, true],
    Number: [false, NaN, 'throw'],
    String: [true, 'abc', 'abc'],
    Date: [false, 'abc', 'throw'],
    Array: [false, 'abc', 'abc'],
    Model: [true, 'abc', 'abc'],
    Error: [false, 'abc', 'throw'],
    RegExp: [false, new _RegExp('abc'), new _RegExp('abc')],
    Any: [true, 'abc', 'abc', 'abc'],
    Mixed: [false, 'abc', 'abc'],
    Embed: [false, {}, 'throw'],
  }],

  ['numeric string', '1', {
    Boolean: [false, true, true],
    Number: [false, 1, 1],
    String: [true, '1', '1'],
    Date: [false, new Date('1'), new Date('1')],
    Array: [false, '1', '1'],
    Model: [true, '1', '1'],
    Error: [false, '1', 'throw'],
    RegExp: [false, new _RegExp('1'), new _RegExp('1')],
    Any: [true, '1', '1', '1'],
    Mixed: [false, '1', '1'],
    Embed: [false, {}, 'throw'],
  }],

  ['numeric string 0', '0', {
    Boolean: [false, true, true],
    Number: [false, 0, 0],
    String: [true, '0', '0'],
    Date: [false, new Date('0'), new Date('0')],
    Array: [false, '1', '1'],
    Model: [true, '0', '0'],
    Error: [false, '0', 'throw'],
    RegExp: [false, new _RegExp('0'), new _RegExp('0')],
    Any: [true, '0', '0', '0'],
    Mixed: [false, '0', '0'],
    Embed: [false, {}, 'throw'],
  }],

  ['true', true, {
    Boolean: [true, true, true],
    Number: [false, 1, 1],
    String: [false, 'true', 'true'],
    Date: [false, new Date(true), new Date(true)],
    Array: [false, true, true],
    Model: [true, true, true],
    Error: [false, true, 'throw'],
    RegExp: [false, true, 'throw'],
    Any: [true, true, true, true],
    Mixed: [false, true, true],
    Embed: [false, {}, 'throw'],
  }],

  ['false', false, {
    Boolean: [true, false, false],
    Number: [false, 0, 0],
    String: [false, 'false', 'false'],
    Date: [false, new Date(false), new Date(false)],
    Array: [false, false, false],
    Model: [true, false, false],
    Error: [false, false, 'throw'],
    RegExp: [false, false, 'throw'],
    Any: [true, false, false, false],
    Mixed: [false, false, false],
    Embed: [false, {}, 'throw'],
  }],

  ['date', date, {
    Boolean: [false, true, true],
    Number: [false, 1454284800000, 1454284800000],
    String: [false, 'Sun Jan 31 2016 19:00:00 GMT-0500 (COT)',
      'Sun Jan 31 2016 19:00:00 GMT-0500 (COT)'],
    Date: [true, date, date],
    Array: [false, date, date],
    Model: [true, date, date],
    Error: [false, date, 'throw'],
    RegExp: [false, date, 'throw'],
    Any: [true, date, date, date],
    Mixed: [false, date, date],
    Embed: [false, {}, 'throw'],
  }],

  ['empty object', {}, {
    Boolean: [false, true, true],
    Number: [false, NaN, 'throw'],
    String: [false, '[object Object]', '[object Object]'],
    Date: [false, {}, 'throw'],
    Array: [false, {}, {}],
    Model: [true, {}, {}],
    Error: [false, {}, 'throw'],
    RegExp: [false, {}, 'throw'],
    Any: [true, {}, {}, {}],
    Mixed: [false, {}, {}],
    Embed: [false, {}, 'throw'],
  }],

  ['Object', object, {
    Boolean: [false, true, true],
    Number: [false, NaN, 'throw'],
    String: [false, '[object Object]', '[object Object]'],
    Date: [false, object, 'throw'],
    Array: [false, object, object],
    Model: [true, object, object],
    Error: [false, object, 'throw'],
    RegExp: [false, object, 'throw'],
    Any: [true, object, object, object],
    Mixed: [false, object, object],
    Embed: [false, {}, 'throw'],
  }],

  ['empty array', [], {
    Boolean: [false, true, true],
    Number: [false, 0, 0],
    String: [false, '', ''],
    Date: [false, [], 'throw'],
    Array: [true, [], []],
    Model: [true, [], []],
    Error: [false, [], 'throw'],
    RegExp: [false, [], 'throw'],
    Any: [true, [], []],
    Mixed: [false, [], []],
    Embed: [false, {}, 'throw'],
  }],

  ['array of numbers', [1, 2, 3], {
    Boolean: [false, true, true],
    Number: [false, NaN, 'throw'],
    String: [false, '1,2,3', '1,2,3'],
    Date: [false, new Date([1, 2, 3]), new Date([1, 2, 3])],
    Array: [true, [], [1, 2, 3]],
    Model: [true, [1, 2, 3], [1, 2, 3]],
    Error: [false, [1, 2, 3], 'throw'],
    RegExp: [false, [1, 2, 3], 'throw'],
    Any: [true, [1, 2, 3], [1, 2, 3], [1, 2, 3]],
    Mixed: [false, [1, 2, 3], [1, 2, 3]],
    Embed: [false, {}, 'throw'],
  }],

  ['Model', model, {
    Boolean: [false, true, true],
    Number: [false, NaN, 'throw'],
    String: [false, '[object Object]', '[object Object]'],
    Date: [false, model, 'throw'],
    Array: [false, model, model],
    Model: [true, model, model],
    Error: [false, model, 'throw'],
    RegExp: [false, model, 'throw'],
    Any: [true, model, model, model],
    Mixed: [false, model, model],
    Embed: [false, {}, 'throw'],
  }],

  ['Error', error, {
    Boolean: [false, true, true],
    Number: [false, NaN, 'throw'],
    String: [false, 'Error: Foo', 'Error: Foo'],
    Date: [false, error, 'throw'],
    Array: [false, error, error],
    Model: [true, error, error],
    Error: [true, {
      message: error.message,
      name: error.name,
      stack: error.stack,
    }, new _Error(error)],
    RegExp: [false, error, 'throw'],
    Any: [true, error, error, error],
    Mixed: [false, error, error],
    Embed: [false, {}, 'throw'],
  }],

  ['RegExp', regex, {
    Boolean: [false, true, true],
    Number: [false, NaN, 'throw'],
    String: [false, '/^abc/i', '/^abc/i'],
    Date: [false, regex, 'throw'],
    Array: [false, regex, regex],
    Model: [true, regex, regex],
    Error: [false, regex, 'throw'],
    RegExp: [true, regex, new _RegExp(regex)],
    Any: [true, regex, regex, regex],
    Mixed: [false, regex, regex],
    Embed: [false, {}, 'throw'],
  }],

  ['Valid mixed', 'http://google.com', {
    Boolean: [false, true, true],
    Number: [false, NaN, 'throw'],
    String: [true, 'http://google.com', 'http://google.com'],
    Date: [false, 'http://google.com', 'throw'],
    Array: [false, 'http://google.com', 'http://google.com'],
    Model: [true, 'http://google.com', 'http://google.com'],
    Error: [false, 'http://google.com', 'throw'],
    RegExp: [false, new _RegExp('http://google.com'),
      new _RegExp('http://google.com')],
    Any: [true, 'http://google.com', 'http://google.com'],
    Mixed: [true, 'http://google.com', 'http://google.com'],
    Embed: [false, {}, 'throw'],
  }],

  ['Invalid mixed', 'hello', {
    Boolean: [false, true, true],
    Number: [false, NaN, 'throw'],
    String: [true, 'hello', 'hello'],
    Date: [false, 'hello', 'throw'],
    Array: [false, 'hello', 'hello'],
    Model: [true, 'hello', 'hello'],
    Error: [false, 'hello', 'throw'],
    RegExp: [false, new _RegExp('hello'), new _RegExp('hello')],
    Any: [true, 'hello', 'hello'],
    Mixed: [false, 'hello', 'hello'],
    Embed: [false, {}, 'throw'],
  }],

  ['Valid embedded', {number: 100}, {
    Boolean: [false, true, true],
    Number: [false, NaN, 'throw'],
    String: [false, '[object Object]', '[object Object]'],
    Date: [false, {number: 100}, 'throw'],
    Array: [false, {number: 100}, {number: 100}],
    Model: [true, {number: 100}, {number: 100}],
    Error: [false, {number: 100}, 'throw'],
    RegExp: [false, {number: 100}, 'throw'],
    Any: [true, {number: 100}, {number: 100}],
    Mixed: [false, {number: 100}, {number: 100}],
    Embed: [true, {number: 100}, {number: 100}],
  }],

  ['Invalid embedded', {number: {}}, {
    Boolean: [false, true, true],
    Number: [false, NaN, 'throw'],
    String: [false, '[object Object]', '[object Object]'],
    Date: [false, {number: {}}, 'throw'],
    Array: [false, {number: {}}, {number: {}}],
    Model: [true, {number: {}}, {number: {}}],
    Error: [false, {number: {}}, 'throw'],
    RegExp: [false, {number: {}}, 'throw'],
    Any: [true, {number: {}}, {number: {}}],
    Mixed: [false, {number: {}}, {number: {}}],
    Embed: [false, {number: NaN}, 'throw'],
  }],

  ['Semi-valid embedded', {number: '1'}, {
    Boolean: [false, true, true],
    Number: [false, NaN, 'throw'],
    String: [false, '[object Object]', '[object Object]'],
    Date: [false, {number: '1'}, 'throw'],
    Array: [false, {number: '1'}, {number: '1'}],
    Model: [true, {number: '1'}, {number: '1'}],
    Error: [false, {number: '1'}, 'throw'],
    RegExp: [false, {number: '1'}, 'throw'],
    Any: [true, {number: '1'}, {number: '1'}],
    Mixed: [false, {number: '1'}, {number: '1'}],
    Embed: [false, {number: 1}, {number: 1}],
  }],
];
